
workspace:
  base: /go
  path: src/github.com/emersonmatsumoto/go-hello-world

pipeline:
  build:
    image: golang:1.8
    dockerfile: Dockerfile
    
compose:
  database:
    image: postgres:9.4.5
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=todo
